### ISSUE TITLE
TCP Server One-to_many communication

### ISSUE THREAD

**Issue by Lj-dog** [famousman/TCP-IP-Socket-Prgramming-Sample#1]
Hi Famousman,
    I am so glad to refer to a sample program which use TcpListener class to bulid a TCP server.
  But this program can just establish one TCP connection.In the actual prduction of practical applications, one server will establish connections with multiple clients.
  Do you have / Could you recommand a sample which use TcpListener class to establish connections with multiple clients.

**Comment by famousman** [comment]
Hi lj-dog
it was a student project and for long time ago. but i think you can use async to make ready to send to and receive from several clients. or open a window (not open app again, by programming) per client.
hope i could help you

**Comment by Lj-dog** [comment]
Thanks, I will give it a try
